synchronize access to namespacePrefixMapper to avoid the following error in multithreaded scenarios
ERROR o.d.o.contenttype.ContentTypeManager 931 - namespacePrefixMapper is null
javax.xml.bind.JAXBException: namespacePrefixMapper is null
	at org.docx4j.jaxb.NamespacePrefixMapperUtils.setProperty(NamespacePrefixMapperUtils.java:164)
	at org.docx4j.openpackaging.contenttype.ContentTypeManager.marshal(ContentTypeManager.java:923)
	at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:265)
	at org.docx4j.openpackaging.io3.Save.save(Save.java:177)